#!/bin/sh

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

sudo apt update && sudo apt install debootstrap -y
debootstrap --include=tzdata,dbus,apt,locales parrot "$CHROOT" 2>/dev/null
cp /etc/calamares/scripts/generate_machineid "$CHROOT"/tmp/generate_machineid
exit 0
